# Generated by Django 2.1.1 on 2018-09-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yinshe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicip', models.CharField(max_length=100, verbose_name='公网ip')),
                ('publicip_port', models.CharField(max_length=100, null=True, verbose_name='公网端口')),
                ('parviteip', models.CharField(max_length=100, verbose_name='内网ip')),
                ('parviteip_port', models.CharField(max_length=100, null=True, verbose_name='内网端口')),
                ('product', models.CharField(max_length=50, null=True, verbose_name='环境')),
                ('Agreement', models.CharField(max_length=50, null=True, verbose_name='协议')),
            ],
            options={
                'verbose_name': '端口映射表',
                'verbose_name_plural': '端口映射表',
            },
        ),
    ]
