# Generated by Django 2.1.1 on 2018-09-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yinshe',
            name='parviteip',
            field=models.CharField(max_length=100, null=True, verbose_name='内网ip'),
        ),
        migrations.AlterField(
            model_name='yinshe',
            name='publicip',
            field=models.CharField(max_length=100, null=True, verbose_name='公网ip'),
        ),
    ]
