# Generated by Django 2.1.1 on 2018-09-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipport', '0002_auto_20180920_1439'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yinshe',
        ),
    ]
