# Generated by Django 2.1.1 on 2018-09-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100, verbose_name='git_version')),
                ('servername', models.CharField(max_length=100, null=True, verbose_name='应用')),
                ('product', models.CharField(max_length=50, null=True, verbose_name='环境')),
            ],
            options={
                'verbose_name_plural': '发布记录',
                'verbose_name': '发布记录',
            },
        ),
    ]
