# Generated by Django 2.1.1 on 2018-09-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deply', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabu',
            options={'verbose_name': '标签', 'verbose_name_plural': '发布记录'},
        ),
    ]
